// apps/web/src/components/container.tsx
import React, { type HTMLAttributes } from "react";

import { cn } from "@/utils/cn";

type ContainerProps = HTMLAttributes<HTMLDivElement> & {
  className?: string;
  layout?: "normal" | "full";
  children: React.ReactNode;
};

export const Container = React.forwardRef<HTMLDivElement, ContainerProps>(
  ({ layout = "normal", className, children, ...props }, ref) => {
    return (
      <div
        ref={ref}
        className={cn(
          "mx-auto flex w-full flex-col px-4 sm:px-6 lg:px-8",
          {
            "max-w-[1200px]": layout === "normal",
            "max-w-full": layout === "full",
          },
          className,
        )}
        {...props}
      >
        {children}
      </div>
    );
  },
);
Container.displayName = "Container";

// apps/vertex/src/lib/components/ui/container.svelte
<script lang="ts">
	import { cn } from '$lib/cn';
	import type { HTMLAttributes } from 'svelte/elements';

	type Props = HTMLAttributes<HTMLDivElement>;

	let { children, class: className, ...props }: Props = $props();
</script>

<div
	class={cn(
		'mx-auto w-full px-4 sm:px-6 lg:px-8 gap-4 max-w-[1200px] flex flex-row py-10',
		className
	)}
	{...props}
>
	{@render children?.()}
</div>
