// apps/web/src/app/(default)/for-studenter/motereferat/[id]/page.tsx
import { cache } from "react";
import { type Metadata } from "next";
import { notFound } from "next/navigation";

import { Container } from "@/components/container";
import { Heading } from "@/components/typography/heading";
import { Button } from "@/components/ui/button";
import { fetchMinuteById } from "@/sanity/minutes/requests";

type Props = {
  params: {
    id: string;
  };
};

const getData = cache(async (id: string) => {
  const minute = await fetchMinuteById(id);

  if (!minute) {
    return notFound();
  }

  return minute;
});

export const generateMetadata = async ({ params }: Props): Promise<Metadata> => {
  const { title } = await getData(params.id);
  return {
    title,
  };
};

export default async function MinutePage({ params }: Props) {
  const minute = await getData(params.id);

  return (
    <Container className="py-10">
      <Heading className="mb-4">{minute.title}</Heading>

      <div className="flex flex-col gap-5">
        {minute.document && (
          <Button className="w-full md:w-fit" asChild>
            <a href={minute.document}>Last ned</a>
          </Button>
        )}

        {minute.document ? (
          <iframe title={minute.title} src={minute.document} className="h-screen w-full" />
        ) : (
          <p>Ingen dokumenter tilgjengelig</p>
        )}
      </div>
    </Container>
  );
}

// apps/vertex/src/routes/(sidebar)/for-studenter/motereferater/[id]/+page.svelte
<script lang="ts">
	import Heading from '$lib/components/ui/heading.svelte';

	let { data } = $props();

	let title = $derived(data.minute.isAllMeeting ? 'Generalforsamling' : 'Møte');
</script>

<Heading>{title}</Heading>

{#if data.minute.document}
	<div class="flex flex-col gap-5">
		<a
			href={data.minute.document}
			class="inline-flex items-center font-semibold justify-center rounded-xl border-2 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none ring-offset-background duration-300 bg-primary border-primary-dark text-primary-foreground hover:bg-primary-hover h-10 py-2 px-4 w-full md:w-fit"
			type="button"
		>
			Last ned
		</a>

		<iframe
			title="{title} {new Date(data.minute.date).toLocaleDateString()}"
			src={data.minute.document}
			class="h-screen w-full"
		></iframe>
	</div>
{:else}
	<p class="text-center text-xl">Ingen dokumenter tilgjengelig</p>
{/if}
