// apps/vertex/src/lib/components/footer/footer.svelte
<script lang="ts">
	import { ExternalLink, GitCommit, Rss } from '@lucide/svelte';
	import Sanity from '$lib/assets/svg/sanity-logo.svg';
	import Bekk from '$lib/assets/images/bekk.png';

	const contactUsLinks = [
		{
			label: 'echo@uib.no',
			href: 'mailto:echo@uib.no'
		},
		{
			label: 'Thormøhlens gate 55 5006 BERGEN',
			href: 'https://goo.gl/maps/adUsBsoZh3QqNvA36'
		},
		{
			label: 'Organisasjonsnummer: 998 995 035',
			href: 'https://w2.brreg.no/enhet/sok/detalj.jsp?orgnr=998995035'
		},
		{
			label: 'Opplevd noe kjipt? Speak up!',
			href: '/for-studenter/speak-up'
		},
		{
			label: 'Personvernerklæring',
			href: '/personvern'
		}
	];

	const socialsLinks = [
		{
			label: 'Facebook',
			href: 'https://www.facebook.com/groups/informatikk'
		},
		{
			label: 'Instagram',
			href: 'https://www.instagram.com/echo_uib/'
		},
		{
			label: 'GitHub',
			href: 'https://github.com/echo-webkom'
		}
	];
</script>

<footer
	class="relative rounded-t-[40px] border-2 border-footer-border bg-footer px-10 py-24 text-footer-foreground"
>
	<!-- Latest commit -->
	<div class="absolute bottom-0 left-0 p-1.5">
		<p class="font-mono text-xs text-muted-foreground">
			<a
				class="flex items-center gap-1 hover:underline"
				href="https://github.com/echo-webkom/echo-web-mono/commit/052a8c60122981aed3b6ee79e246421c51dfb8a3"
			>
				<GitCommit class="size-4" />
				052a8c6
			</a>
		</p>
	</div>

	<!-- Link to RSS feed -->
	<div class="absolute bottom-0 left-1/2 -translate-x-1/2 p-1.5">
		<ul class="flex flex-row gap-2 font-mono text-xs text-muted-foreground">
			<li>
				<a class="flex items-center gap-1 hover:underline" href="/feed">
					<Rss class="size-4" />
					RSS Feed
				</a>
			</li>
		</ul>
	</div>

	<div class="mx-auto flex w-full max-w-7xl">
		<div class="flex w-full flex-wrap justify-between gap-10 sm:gap-20">
			<div>
				<h3 class="mb-4 py-2 text-xl font-bold">Kontakt oss ☎️</h3>
				<ul class="space-y-1">
					<li>
						{#each contactUsLinks as link}
							{@const isExternal = link.href.startsWith('http')}
							{#if isExternal}
								<a
									class="flex items-center gap-2 hover:underline"
									target="_blank"
									rel="noreferrer"
									href={link.href}
									>{link.label} <ExternalLink class="size-3" />
								</a>
							{:else}
								<a class="flex items-center gap-2 hover:underline" href={link.href}
									>{link.label}
								</a>
							{/if}
						{/each}
					</li>
				</ul>
			</div>
			<div>
				<h3 class="mb-4 py-2 text-xl font-bold">Følg oss 💻</h3>
				<ul class="space-y-1">
					{#each socialsLinks as social}
						<li>
							<a
								class="flex items-center gap-2 hover:underline"
								target="_blank"
								rel="noreferrer"
								href={social.href}>{social.label} <ExternalLink class="size-3" /></a
							>
						</li>
					{/each}
				</ul>
			</div>
			<div>
				<h3 class="mb-4 py-2 text-xl font-bold">Hovedsamarbeidspartner 💘</h3>
				<a target="_blank" rel="noreferrer" href="https://bekk.no"
					><img src={Bekk} alt="Bekk logo" class="h-28 w-auto invert dark:invert-0" /></a
				>
			</div>
			<div>
				<h3 class="mb-4 py-2 text-xl font-bold">Powered by 🔧</h3>
				<ul class="space-y-5">
					<li>
						<a target="_blank" rel="noreferrer" href="https://www.sanity.io/">
							<img src={Sanity} alt="Sanity logo" />
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer>

// apps/web/src/components/Footer.tsx
import Link from "next/link";

import {footerRoutes} from "@/lib/routes";
import Image from "next/image";
import classNames from "classnames";
import {getHoverShadow, sponsors} from "@/lib/sponsors";
import {ExternalLinkIcon} from "@radix-ui/react-icons";

export const Footer = () => {
  return (
    <div>
      {/* Footer wave */}
      <svg
        id="svg"
        viewBox="0 0 1440 390"
        xmlns="http://www.w3.org/2000/svg"
        className="h-40 w-full transition delay-150 duration-300 ease-in-out"
        preserveAspectRatio="none"
      >
        <path
          d="M 0,400 C 0,400 0,200 0,200 C 65.93076923076924,224.9153846153846 131.8615384615385,249.83076923076922 205,242 C 278.1384615384615,234.16923076923078 358.4846153846154,193.59230769230768 451,181 C 543.5153846153846,168.40769230769232 648.2000000000002,183.8 737,203 C 825.7999999999998,222.2 898.7153846153847,245.20769230769233 975,244 C 1051.2846153846153,242.79230769230767 1130.9384615384615,217.36923076923074 1209,206 C 1287.0615384615385,194.63076923076926 1363.5307692307692,197.31538461538463 1440,200 C 1440,200 1440,400 1440,400 Z"
          stroke="none"
          strokeWidth="0"
          fill="#ffeabb"
          fillOpacity="1"
          className="path-0 transition-all delay-150 duration-300 ease-in-out"
        ></path>
      </svg>

      {/* Footer */}
      <footer className="bg-echo-yellow2 px-10 py-10">
        <div className="mx-auto w-full max-w-6xl">
          <div className="flex flex-wrap gap-10 sm:gap-20">
            {footerRoutes.map((route) => (
              <div key={route.label}>
                <h3 className="mb-4 py-2 text-xl font-bold">{route.label}</h3>
                <ul className="space-y-1">
                  {route.sublinks.map(({label, href, isExternal}) => (
                    <li key={label}>
                      <Link
                        className="flex items-center gap-2 text-black/80 hover:underline"
                        href={href}
                        {...(isExternal && {
                          target: "_blank",
                          rel: "noreferrer",
                        })}
                      >
                        {label}

                        {/* Add external link icon */}
                        {isExternal && (
                          <span>
                            <ExternalLinkIcon />
                          </span>
                        )}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            ))}

            {/* Main sponsor */}
            <div>
              <h3 className="mb-4 py-2 text-xl font-bold">
                💘 Hovedsamarbeidspartner
              </h3>
              <Link href="https://bekk.no">
                <Image
                  src="/images/bekk.png"
                  className="invert"
                  height={250}
                  width={250}
                  alt="Bekk logo"
                />
              </Link>
            </div>

            {/* Other sponsors */}
            <div>
              <h3 className="mb-4 py-2 text-xl font-bold">🔧 Powered by</h3>
              <ul className="space-y-5">
                {sponsors.map(({label, href, imageSrc}) => {
                  const shadowColor = getHoverShadow(label);

                  return (
                    <li key={label}>
                      <Link href={href}>
                        <Image
                          src={imageSrc}
                          className={classNames(
                            "rounded-lg bg-white px-5 py-3 shadow-md transition-shadow duration-300 ease-in-out",
                            shadowColor,
                          )}
                          height={150}
                          width={150}
                          alt={`${label} logo`}
                        />
                      </Link>
                    </li>
                  );
                })}
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};
