// apps/vertex/src/lib/components/footer/footer.svelte
<script lang="ts">
	import { ExternalLink, GitCommit, Rss } from '@lucide/svelte';
	import { PUBLIC_COMMIT_HASH } from '$env/static/public';
	import Sanity from '$lib/assets/svg/sanity-logo.svg';
	import Bekk from '$lib/assets/images/bekk.png';

	const contactUsLinks = [
		{
			label: 'echo@uib.no',
			href: 'mailto:echo@uib.no'
		},
		{
			label: 'Thormøhlens gate 55 5006 BERGEN',
			href: 'https://goo.gl/maps/adUsBsoZh3QqNvA36'
		},
		{
			label: 'Organisasjonsnummer: 998 995 035',
			href: 'https://w2.brreg.no/enhet/sok/detalj.jsp?orgnr=998995035'
		},
		{
			label: 'Opplevd noe kjipt? Speak up!',
			href: '/for-studenter/speak-up'
		},
		{
			label: 'Personvernerklæring',
			href: '/personvern'
		}
	];

	const socialsLinks = [
		{
			label: 'Facebook',
			href: 'https://www.facebook.com/groups/informatikk'
		},
		{
			label: 'Instagram',
			href: 'https://www.instagram.com/echo_uib/'
		},
		{
			label: 'GitHub',
			href: 'https://github.com/echo-webkom'
		}
	];

	const displayHash = PUBLIC_COMMIT_HASH === '' ? null : PUBLIC_COMMIT_HASH.slice(0, 7);
</script>

<footer
	class="relative rounded-t-[40px] border-2 border-footer-border bg-footer px-10 py-24 text-footer-foreground"
>
	<!-- Latest commit -->
	{#if displayHash}
		<div class="absolute bottom-0 left-0 p-1.5">
			<p class="font-mono text-xs text-muted-foreground">
				<a
					class="flex items-center gap-1 hover:underline"
					href="https://github.com/echo-webkom/echo-web-mono/commit/{PUBLIC_COMMIT_HASH}"
				>
					<GitCommit class="size-4" />
					{displayHash}
				</a>
			</p>
		</div>
	{/if}

	<!-- Link to RSS feed -->
	<div class="absolute bottom-0 left-1/2 -translate-x-1/2 p-1.5">
		<ul class="flex flex-row gap-2 font-mono text-xs text-muted-foreground">
			<li>
				<a class="flex items-center gap-1 hover:underline" href="/feed">
					<Rss class="size-4" />
					RSS Feed
				</a>
			</li>
		</ul>
	</div>

	<div class="mx-auto flex w-full max-w-7xl">
		<div class="flex w-full flex-wrap justify-between gap-10 sm:gap-20">
			<div>
				<h3 class="mb-4 py-2 text-xl font-bold">Kontakt oss ☎️</h3>
				<ul class="space-y-1">
					<li>
						{#each contactUsLinks as link}
							{@const isExternal = link.href.startsWith('http')}
							{#if isExternal}
								<a
									class="flex items-center gap-2 hover:underline"
									target="_blank"
									rel="noreferrer"
									href={link.href}
									>{link.label} <ExternalLink class="size-3" />
								</a>
							{:else}
								<a class="flex items-center gap-2 hover:underline" href={link.href}
									>{link.label}
								</a>
							{/if}
						{/each}
					</li>
				</ul>
			</div>
			<div>
				<h3 class="mb-4 py-2 text-xl font-bold">Følg oss 💻</h3>
				<ul class="space-y-1">
					{#each socialsLinks as social}
						<li>
							<a
								class="flex items-center gap-2 hover:underline"
								target="_blank"
								rel="noreferrer"
								href={social.href}>{social.label} <ExternalLink class="size-3" /></a
							>
						</li>
					{/each}
				</ul>
			</div>
			<div>
				<h3 class="mb-4 py-2 text-xl font-bold">Hovedsamarbeidspartner 💘</h3>
				<a target="_blank" rel="noreferrer" href="https://bekk.no"
					><img src={Bekk} alt="Bekk logo" class="h-28 w-auto invert dark:invert-0" /></a
				>
			</div>
			<div>
				<h3 class="mb-4 py-2 text-xl font-bold">Powered by 🔧</h3>
				<ul class="space-y-5">
					<li>
						<a target="_blank" rel="noreferrer" href="https://www.sanity.io/">
							<img src={Sanity} alt="Sanity logo" />
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer>

// apps/web/src/components/footer.tsx
import { type StaticImport } from "next/dist/shared/lib/get-img-props";
import Image from "next/image";
import Link from "next/link";
import { BiRss } from "react-icons/bi";
import { MdCommit } from "react-icons/md";
import { RxExternalLink as ExternalLink } from "react-icons/rx";

import BekkLogo from "@/assets/images/bekk.png";
import { footerRoutes } from "@/lib/routes";
import { sponsors } from "@/lib/sponsors";
import { cn } from "@/utils/cn";

type FooterProps = {
  className?: string;
};

export const Footer = ({ className }: FooterProps) => {
  return (
    <div className={cn("mt-32 selection:bg-primary", className)}>
      <footer className="relative rounded-t-[40px] border-2 border-footer-border bg-footer px-10 py-24 text-footer-foreground">
        <CommitLabel />
        <UsefulLinks />

        <div className="mx-auto flex w-full max-w-7xl">
          <div className="flex w-full flex-wrap justify-between gap-10 sm:gap-20">
            {footerRoutes.map((section) => {
              return (
                <div key={section.label}>
                  <h3 className="mb-4 py-2 text-xl font-bold">{section.label}</h3>
                  <ul className="space-y-1">
                    {section.sublinks.map(({ href, label, isExternal }) => {
                      return (
                        <li key={label}>
                          <Link
                            className="flex items-center gap-2 hover:underline"
                            href={href}
                            {...(isExternal && {
                              target: "_blank",
                              rel: "noreferrer",
                            })}
                          >
                            {label}

                            {isExternal && (
                              <span>
                                <ExternalLink />
                              </span>
                            )}
                          </Link>
                        </li>
                      );
                    })}
                  </ul>
                </div>
              );
            })}

            {/* Main sponsor */}
            <div>
              <h3 className="mb-4 py-2 text-xl font-bold">Hovedsamarbeidspartner 💘</h3>
              <Link href="https://bekk.no" target="_blank" rel="noreferrer">
                <Image
                  src={BekkLogo as StaticImport}
                  className="h-28 w-auto invert dark:invert-0"
                  alt="Bekk logo"
                />
              </Link>
            </div>

            {/* Other sponsors */}
            <div>
              <h3 className="mb-4 py-2 text-xl font-bold">Powered by 🔧</h3>
              <ul className="space-y-5">
                {sponsors.map(({ label, href, imageSrc }) => (
                  <li key={label}>
                    <Link href={href} target="_blank" rel="noreferrer">
                      <Image
                        src={imageSrc as StaticImport}
                        alt={`${label} logo`}
                        className={cn("h-8 w-auto", label === "Vercel" && "invert-0 dark:invert")}
                      />
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

const COMMIT_SHA = process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA ?? "AAAAAAAAAAAAAAAAAAAAA";
const humanSha = COMMIT_SHA.slice(0, 7);

const CommitLabel = () => {
  return (
    <div className="absolute bottom-0 left-0 p-1.5">
      <p className="font-mono text-xs text-muted-foreground">
        <a
          className="flex items-center gap-1 hover:underline"
          href={`https://github.com/echo-webkom/echo-web-mono/commit/${COMMIT_SHA}`}
        >
          <MdCommit className="inline-block h-4 w-4" />
          {humanSha}
        </a>
      </p>
    </div>
  );
};

const UsefulLinks = () => {
  return (
    <div className="absolute bottom-0 left-1/2 -translate-x-1/2 p-1.5">
      <ul className="flex flex-row gap-2 font-mono text-xs text-muted-foreground">
        <li>
          <Link className="flex items-center gap-1 hover:underline" href="/feed">
            <BiRss className="inline-block h-4 w-4" />
            RSS Feed
          </Link>
        </li>
      </ul>
    </div>
  );
};
