// apps/beta/src/lib/components/ui/form/checkbox.svelte
<script lang="ts">
	import { Checkbox, useId, type WithoutChildrenOrChild } from 'bits-ui';
	import { Check, Minus } from '@lucide/svelte';
	import { cn } from '$lib/cn';

	let {
		id: propId,
		class: className,
		name,
		checked = $bindable(false),
		ref = $bindable(null),
		...restProps
	}: WithoutChildrenOrChild<Checkbox.RootProps> = $props();
	const id = propId ?? name ?? useId();
</script>

<Checkbox.Root
	{id}
	class={cn(
		'flex size-4 items-center justify-center rounded-md border-2',
		'transition duration-200 ease-in-out',
		'focus:ring-primary focus:ring-2 focus:ring-offset-2 focus:outline-none',
		{
			'bg-primary text-primary-foreground border-transparent': checked
		},
		className
	)}
	bind:checked
	bind:ref
	{...restProps}
>
	{#snippet children({ checked, indeterminate })}
		{#if indeterminate}
			<Minus class="size-4 stroke-3" />
		{:else if checked}
			<Check class="size-4 stroke-3" />
		{/if}
	{/snippet}
</Checkbox.Root>

{#if name}
	<input type="hidden" {name} value={checked ? 'on' : 'off'} />
{/if}

// apps/web/src/components/ui/checkbox.tsx
"use client";

import { CheckIcon } from "lucide-react";
import { Checkbox as CheckboxPrimitive } from "radix-ui";
import * as React from "react";

import { cn } from "@/utils/cn";

function Checkbox({ className, ...props }: React.ComponentProps<typeof CheckboxPrimitive.Root>) {
  return (
    <CheckboxPrimitive.Root
      data-slot="checkbox"
      className={cn(
        "peer border-primary ring-offset-background data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground focus-visible:ring-ring h-4 w-4 shrink-0 rounded-sm border focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-hidden disabled:cursor-not-allowed disabled:opacity-50",
        className,
      )}
      {...props}
    >
      <CheckboxPrimitive.Indicator
        data-slot="checkbox-indicator"
        className="grid place-content-center text-current transition-none [&>svg]:size-3.5"
      >
        <CheckIcon />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  );
}

export { Checkbox };
