// apps/beta/src/lib/components/ui/form/label.svelte
<script lang="ts">
	import type { HTMLLabelAttributes } from 'svelte/elements';
	import { cn } from '$lib/cn';

	type Props = HTMLLabelAttributes & {
		required?: boolean;
	};

	let { children, class: className, required, ...props }: Props = $props();
</script>

<label
	class={cn(
		'text-sm leading-none font-semibold peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
		className
	)}
	{...props}
>
	{@render children?.()}
	{#if required}
		<span class="text-sm text-red-500" aria-hidden="true">*</span>
	{/if}
</label>

// apps/web/src/components/ui/label.tsx
import * as React from "react";
import * as LabelPrimitive from "@radix-ui/react-label";
import cn from "classnames";

export type LabelProps = React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root> & {
  required?: boolean;
};

const Label = React.forwardRef<React.ElementRef<typeof LabelPrimitive.Root>, LabelProps>(
  ({className, required, children, ...props}, ref) => (
    <LabelPrimitive.Root
      ref={ref}
      className={cn(
        "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
        className,
      )}
      {...props}
    >
      {children}
      {required && (
        <span className="ml-1 text-red-500" aria-hidden="true">
          *
        </span>
      )}
    </LabelPrimitive.Root>
  ),
);
Label.displayName = LabelPrimitive.Root.displayName;

export {Label};
