// apps/beta/src/lib/components/ui/form/select.svelte
<script lang="ts">
	import type { HTMLSelectAttributes } from 'svelte/elements';

	type Props = HTMLSelectAttributes;

	let { value = $bindable(), children, class: className, ...props }: Props = $props();
</script>

<select
	bind:value
	class={[
		'border-border bg-input ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex h-10 w-full items-center justify-between rounded-md border-2 px-3 py-2 text-sm font-semibold focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50',
		className
	]}
	{...props}
>
	{@render children?.()}
</select>

// apps/web/src/components/ui/select.tsx
"use client";

import React from "react";
import clsx from "clsx";

export const Select = React.forwardRef<HTMLSelectElement, React.ComponentPropsWithoutRef<"select">>(
  ({ children, value, ...props }, ref) => (
    <select
      ref={ref}
      className={clsx(
        "flex h-10 w-full items-center justify-between rounded-md border border-border bg-input px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
        value ? "text-foreground" : "text-muted-foreground" ,
      )}
      defaultValue={value}
      {...props}
    >
      {children}
    </select>
  ),
);
Select.displayName = "Select";
