// apps/web/src/app/(default)/for-studenter/utlan/[slug]/page.tsx
import { cache } from "react";
import Image from "next/image";
import { notFound } from "next/navigation";

import { urlFor } from "@echo-webkom/sanity";

import { Container } from "@/components/container";
import { Markdown } from "@/components/markdown";
import { Heading } from "@/components/typography/heading";
import { Text } from "@/components/typography/text";
import { fetchUtlanBySlug } from "@/sanity/utlan";

type Props = {
  params: Promise<{
    slug: string;
  }>;
};

const getData = cache(async (slug: string) => {
  const utlan = await fetchUtlanBySlug(slug);

  if (!utlan) {
    return notFound();
  }

  return utlan;
});

export const generateMetadata = async (props: Props) => {
  const params = await props.params;
  const utlan = await getData(params.slug);

  return {
    title: utlan.title,
  };
};

export default async function UtlanPage(props: Props) {
  const params = await props.params;
  const utlan = await getData(params.slug);

  return (
    <Container className="mx-auto max-w-4xl space-y-5 px-6 py-10">
      <Heading className="text-3xl font-bold">{utlan.title}</Heading>

      <Image
        src={urlFor(utlan.image).url()}
        alt={utlan.title}
        width={700}
        height={475}
        className="rounded-lg border-2 shadow-lg"
      />

      <Text className="text-md font-semibold">
        Send mail til <span className="underline">echo@uib.no</span> for kjøp
      </Text>

      {utlan.body && (
        <div>
          <Heading className="mb-2 text-lg font-semibold">Beskrivelse</Heading>
          <Markdown content={utlan.body} />
        </div>
      )}
    </Container>
  );
}

// apps/beta/src/routes/(sidebar)/for-studenter/merch/[slug]/+page.svelte
<script lang="ts">
	import { urlFor } from '$lib/sanity/image';
	import Heading from '$lib/components/ui/heading.svelte';

	let { data } = $props();
</script>

<section class="mx-auto max-w-5xl px-6 py-12">
	<div class="flex flex-col items-center gap-10 md:flex-row md:items-start">
		<!-- 🖼️ Image Section -->
		<div class="block w-full max-w-full flex-shrink-0 md:w-[300px]">
			<img
				alt={data.merch.title}
				src={urlFor(data.merch.image).url()}
				class="h-auto max-h-[400px] w-full rounded-xl border border-gray-300 object-cover shadow-md"
			/>
		</div>

		<!-- 📦 Info Section -->
		<div class="flex-1 text-center md:text-left">
			<Heading class="mb-4 text-4xl font-bold">{data.merch.title}</Heading>

			<p class="mb-2 text-lg font-semibold">
				Pris:
				<span class="text-primary text-xl">{data.merch.price} kr</span>
			</p>

			<p class="text-md mb-6 font-medium">
				Send mail til
				<a href="mailto:echo@uib.no" class="text-blue-600 underline transition hover:text-blue-800"
					>echo@uib.no</a
				>
				for kjøp
			</p>

			<a
				href="mailto:echo@uib.no?subject=Kjøp%20av%20{encodeURIComponent(data.merch.title)}"
				class="btn-primary"
			>
				Send forespørsel
			</a>
		</div>
	</div>
</section>
