// apps/vertex/src/routes/om/brosjyre/+page.svelte
<script lang="ts">
	import StaticPagesSiderbar from '$lib/components/static-pages-siderbar.svelte';
	import Container from '$lib/components/ui/container.svelte';
	import Heading from '$lib/components/ui/heading.svelte';
</script>

<Container>
	<StaticPagesSiderbar />

	<div class="w-full">
		<Heading>Brosjyre</Heading>
		<iframe title="echo-brosjyre" style="width: 100%; height: 800px;" src="/echo-oppslag.pdf"
		></iframe>
	</div>
</Container>

// apps/web/src/app/(default)/om/brosjyre/page.tsx
import { getNewPageMetadata } from "@/app/seo";
import { Container } from "@/components/container";
import { Heading } from "@/components/typography/heading";

export const metadata = getNewPageMetadata("Brosjyre", "Brosjyren til echo");

export default function Brochure() {
  return (
    <Container className="space-y-8 py-10">
      <Heading>Brosjyre</Heading>
      <iframe
        title="echo-brosjyre"
        style={{
          width: "100%",
          height: "800px",
        }}
        src="/echo-oppslag.pdf"
      ></iframe>
    </Container>
  );
}
