// apps/web/src/app/(default)/for-studenter/motereferat/[id]/page.tsx
import { cache } from "react";
import { type Metadata } from "next";
import { notFound } from "next/navigation";

import { Container } from "@/components/container";
import { Heading } from "@/components/typography/heading";
import { Button } from "@/components/ui/button";
import { fetchMinuteById } from "@/sanity/minutes/requests";

type Props = {
  params: {
    id: string;
  };
};

const getData = cache(async (id: string) => {
  const minute = await fetchMinuteById(id);

  if (!minute) {
    return notFound();
  }

  return minute;
});

export const generateMetadata = async ({ params }: Props): Promise<Metadata> => {
  const { title } = await getData(params.id);
  return {
    title,
  };
};

export default async function MinutePage({ params }: Props) {
  const minute = await getData(params.id);

  return (
    <Container className="py-10">
      <Heading className="mb-4">{minute.title}</Heading>

      <div className="flex flex-col gap-5">
        {minute.document && (
          <Button className="w-full md:w-fit" asChild>
            <a href={minute.document}>Last ned</a>
          </Button>
        )}

        {minute.document ? (
          <iframe title={minute.title} src={minute.document} className="h-screen w-full" />
        ) : (
          <p>Ingen dokumenter tilgjengelig</p>
        )}
      </div>
    </Container>
  );
}

// apps/beta/src/routes/(app)/for-studenter/motereferat/[id]/+page.svelte
<script lang="ts">
	import ButtonLink from '$lib/components/ui/ButtonLink.svelte';

	let { data } = $props();
</script>

<h1 class="mb-4 text-2xl font-medium">{data.minute.title}</h1>

<div class="flex flex-col gap-5">
	{#if data.minute.document}
		<ButtonLink href={data.minute.document} class="w-full md:w-fit">Last ned</ButtonLink>
		<iframe title={data.minute.title} src={data.minute.document} class="h-screen w-full"></iframe>
	{:else}
		<p class="py-8 text-center text-xl font-medium">Ingen dokumenter tilgjengelig</p>
	{/if}
</div>
