// apps/web/src/app/(default)/about/minute/[id]/page.tsx
import {type Metadata} from "next";

import Container from "@/components/container";
import {Button} from "@/components/ui/button";
import Heading from "@/components/ui/heading";
import {fetchMinuteById, fetchMinuteParams} from "@/sanity/minutes";

export const dynamicParams = false;

type Props = {
  params: {
    id: string;
  };
};

async function getData(id: string) {
  return await fetchMinuteById(id);
}

export async function generateStaticParams() {
  return await fetchMinuteParams();
}

export async function generateMetadata({params}: Props): Promise<Metadata> {
  const {title} = await getData(params.id);
  return {
    title,
  };
}

export default async function MinutePage({params}: Props) {
  const minute = await getData(params.id);

  return (
    <Container>
      <Heading>{minute.title}</Heading>

      <div className="flex flex-col gap-5">
        <Button className="w-full md:w-fit" asChild>
          <a href={minute.document}>Last ned</a>
        </Button>

        <iframe title={minute.title} src={minute.document} className="h-screen w-full" />
      </div>
    </Container>
  );
}

// apps/beta/src/routes/(app)/for-studenter/motereferat/[id]/+page.svelte
<script lang="ts">
	import ButtonLink from '$lib/components/ui/ButtonLink.svelte';

	let { data } = $props();
</script>

<h1 class="mb-4 text-2xl font-medium">{data.minute.title}</h1>

<div class="flex flex-col gap-5">
	{#if data.minute.document}
		<ButtonLink href={data.minute.document} class="w-full md:w-fit">Last ned</ButtonLink>
		<iframe title={data.minute.title} src={data.minute.document} class="h-screen w-full"></iframe>
	{:else}
		<p class="py-8 text-center text-xl font-medium">Ingen dokumenter tilgjengelig</p>
	{/if}
</div>
