// apps/vertex/src/lib/components/ui/heading.svelte
<script lang="ts">
	import { cn } from '$lib/cn';
	import type { HTMLAttributes } from 'svelte/elements';

	type Props = HTMLAttributes<HTMLHeadingElement>;

	let { children, class: className, ...props }: Props = $props();
</script>

<h1
	class={cn('group flex items-center font-semibold tracking-tight text-4xl mb-4', className)}
	{...props}
>
	{@render children?.()}
</h1>

// apps/web/src/components/typography/heading.tsx
import React from "react";

import { cn } from "@/utils/cn";

export type HeadingProps = {
  level?: 1 | 2 | 3;
  className?: string;
  children: React.ReactNode;
};

export const Heading = React.forwardRef<HTMLHeadingElement, HeadingProps>(
  ({ level = 1, className, children }, ref) => {
    const Comp = `h${level}` as const;

    return (
      <Comp
        ref={ref}
        className={cn(
          "font-semibold tracking-tight",
          {
            "text-4xl": level === 1,
            "text-3xl": level === 2,
            "text-2xl": level === 3,
          },
          className,
        )}
      >
        {children}
      </Comp>
    );
  },
);
Heading.displayName = "Heading";
