// src/app/(web)/(default)/for-studenter/motereferater/page.tsx
import Link from "next/link";
import { RxArrowRight } from "react-icons/rx";

import { Container } from "@/components/container";
import { Heading } from "@/components/typography/heading";
import { Text } from "@/components/typography/text";
import { fetchMinutes } from "@/sanity/minutes/requests";
import { shortDateNoTime } from "@/utils/date";

export default async function MinuteOverview() {
  const minutes = await fetchMinutes();

  return (
    <Container className="py-10">
      <Heading className="mb-4">Møtereferater</Heading>
      <ul className="divide-y border">
        {minutes.map((minute) => (
          <li key={minute._id}>
            <Link href={"/for-studenter/motereferat/" + minute._id}>
              <div className="group flex items-center justify-between px-5 py-5 transition-all hover:bg-muted hover:py-10">
                <div className="flex w-full flex-col sm:flex-row sm:items-center sm:justify-between">
                  <Text size="lg">{minute.isAllMeeting ? "Generalforsamling" : "Møte"}</Text>

                  <div className="flex items-center gap-2">
                    <p>{shortDateNoTime(minute.date)}</p>
                    <RxArrowRight className="hidden h-8 w-8 rounded border p-2 sm:block" />
                  </div>
                </div>

                <div className="block sm:hidden">
                  <RxArrowRight className="h-10 w-10 rounded border p-2" />
                </div>
              </div>
            </Link>
          </li>
        ))}
      </ul>
    </Container>
  );
}

// apps/beta/src/routes/(sidebar)/for-studenter/motereferater/+page.svelte
<script lang="ts">
	import { ArrowRight } from '@lucide/svelte';
	import { format } from 'date-fns';
	import { nb } from 'date-fns/locale';

	let { data } = $props();
</script>

<ul class="divide-y overflow-hidden rounded-lg border">
	{#each data.minutes as minute}
		{@const type = minute.isAllMeeting ? 'Generalforsamling' : 'Møte'}
		<li>
			<a href="/for-studenter/motereferater/{minute._id}"
				><div
					class="group hover:bg-muted flex w-full items-center justify-between px-5 py-5 transition-all hover:py-10"
				>
					<div class="flex w-full flex-col sm:flex-row sm:items-center sm:justify-between">
						<p class="py-1 text-xl break-words">{type}</p>
						<div class="flex items-center gap-2">
							<p>{format(minute.date, 'dd. eee. yyyy', { locale: nb })}</p>

							<ArrowRight class="hidden size-8 rounded border p-2 sm:block" />
						</div>
					</div>

					<div class="block sm:hidden">
						<ArrowRight class="size-10 rounded border p-2" />
					</div>
				</div>
			</a>
		</li>
	{/each}
</ul>
