// apps/web/src/app/(default)/webkom/page.tsx
import Image from "next/image";
import { FaCrown } from "react-icons/fa";

import Webkom from "@/assets/images/webkom.png";
import { Container } from "@/components/container";
import { Heading } from "@/components/typography/heading";
import { UnorderedList } from "@/components/typography/list";
import { ListItem } from "@/components/typography/list-item";
import { Text } from "@/components/typography/text";

export default function WebkomPage() {
  return (
    <Container className="py-10 text-center">
      <Image className="mx-auto h-32 w-auto" src={Webkom} alt="Webkom logo" />
      <Heading className="mx-auto font-display">Webkom</Heading>
      {/* Slack ble laget 5. aug 2020 */}
      <Text className="text-xs text-muted-foreground">EST. 2020</Text>

      <Text className="text-muted-foreground">
        Tidligere og nåværende medlemmer av echo Webkom.
      </Text>

      <div className="mx-auto my-10 max-w-md space-y-8">
        <UnorderedList className="list-none p-0 text-lg">
          <ListItem className="relative mx-auto w-fit">
            <FaCrown className="absolute -left-6 top-1 text-yellow-400" />
            <span>Andreas Bakseter (Co-founder)</span>
          </ListItem>
          <ListItem className="relative mx-auto w-fit">
            <FaCrown className="absolute -left-6 top-1 text-yellow-400" />
            <span>Bo Aanes (Co-founder)</span>
          </ListItem>
        </UnorderedList>

        <UnorderedList className="list-none p-0 text-lg">
          <ListItem>Alvar Hønsi</ListItem>
          <ListItem>Øyvind Grutle</ListItem>
          <ListItem>Sander Sigmundstad</ListItem>
          <ListItem>Victoria Valner</ListItem>
        </UnorderedList>

        {/* --- H21 --- */}
        <UnorderedList className="list-none p-0 text-lg">
          <ListItem>Nikolaus Engh</ListItem>
          <ListItem>Ole Magnus Fon Johnsen</ListItem>
          <ListItem>Mathilde Bergenheim</ListItem>
          <ListItem>Thea Jenny Kolnes</ListItem>
          <ListItem>Felix Kaasa</ListItem>
        </UnorderedList>

        {/* --- H22 --- */}
        <UnorderedList className="list-none p-0 text-lg">
          <ListItem>Torger Bocianowski</ListItem>
          <ListItem>Malin Torset Sivertstøl</ListItem>
          <ListItem>Karolina Gil</ListItem>
          <ListItem>Leoul Zinaye Tefera</ListItem>
          <ListItem>Kjetil Alvestad</ListItem>
          <ListItem>Jonas Hammerseth</ListItem>
        </UnorderedList>

        {/* --- H23 --- */}
        <UnorderedList className="list-none p-0 text-lg">
          <ListItem>Johanne Blikberg Herheim</ListItem>
          <ListItem>Kristian Elde Johansen</ListItem>
          <ListItem>Swarnika Sellathurai</ListItem>
          <ListItem>Zeno Elio Leonardi</ListItem>
          <ListItem>Izaak Sarnecki</ListItem>
          <ListItem>Wengeal Abebe</ListItem>
          <ListItem>Hermann Holstad Walaunet</ListItem>
        </UnorderedList>

        {/* --- V24 --- */}

        {/* --- H24 --- */}
        <UnorderedList className="list-none p-0 text-lg">
          <ListItem>Andreas Drevdal</ListItem>
          <ListItem>Birk Monsen</ListItem>
        </UnorderedList>
      </div>
    </Container>
  );
}

// apps/beta/src/routes/(banter)/webkom/+page.svelte
<script lang="ts">
	import Container from '$lib/components/ui/container.svelte';
	import Heading from '$lib/components/ui/heading.svelte';
	import WebkomLogo from '$lib/assets/images/webkom.png';
	import { Crown } from '@lucide/svelte';
</script>

<Container class="flex-col text-center">
	<div>
		<img alt="Webkom logo" class="mx-auto h-32 w-auto" src={WebkomLogo} />
		<Heading class="mx-auto w-fit font-mono">Webkom</Heading>

		<!-- Forslag om å opprette gruppe var 28. jul 2020 -->
		<!-- Slack ble laget 5. aug 2020 -->
		<p class="text-muted-foreground py-1 text-xs break-words">EST. 2020</p>
		<p class="text-muted-foreground py-1 text-lg break-words">
			Tidligere og nåværende medlemmer av echo Webkom.
		</p>
	</div>

	<div class="mx-auto my-10 max-w-md space-y-8">
		<ul class="list-none space-y-1 p-0 text-lg">
			<li class="relative mx-auto w-fit text-lg">
				<Crown class="absolute top-1 -left-6 size-4 fill-yellow-400 text-yellow-400" />
				<span>Andreas Bakseter (Co-founder)</span>
			</li>
			<li class="relative mx-auto w-fit text-lg">
				<Crown class="absolute top-1 -left-6 size-4 fill-yellow-400 text-yellow-400" />
				<span>Bo Aanes (Co-founder)</span>
			</li>
		</ul>

		<!-- H20 -->
		<ul class="list-none space-y-1 p-0 text-lg">
			<li class="text-lg">Alvar Hønsi</li>
			<li class="text-lg">Øyvind Grutle</li>
			<li class="text-lg">Sander Sigmundstad</li>
			<li class="text-lg">Victoria Valner</li>
		</ul>

		<!-- H21 -->
		<ul class="list-none space-y-1 p-0 text-lg">
			<li class="text-lg">Nikolaus Engh</li>
			<li class="text-lg">Ole Magnus Fon Johnsen</li>
			<li class="text-lg">Mathilde Bergenheim</li>
			<li class="text-lg">Thea Jenny Kolnes</li>
			<li class="text-lg">Felix Kaasa</li>
		</ul>

		<!-- H22 -->
		<ul class="list-none space-y-1 p-0 text-lg">
			<li class="text-lg">Torger Bocianowski</li>
			<li class="text-lg">Malin Torset Sivertstøl</li>
			<li class="text-lg">Karolina Gil</li>
			<li class="text-lg">Leoul Zinaye Tefera</li>
			<li class="text-lg">Kjetil Alvestad</li>
			<li class="text-lg">Jonas Hammerseth</li>
		</ul>

		<!-- H23 -->
		<ul class="list-none space-y-1 p-0 text-lg">
			<li class="text-lg">Johanne Blikberg Herheim</li>
			<li class="text-lg">Kristian Elde Johansen</li>
			<li class="text-lg">Swarnika Sellathurai</li>
			<li class="text-lg">Zeno Elio Leonardi</li>
			<li class="text-lg">Izaak Sarnecki</li>
			<li class="text-lg">Wengeal Abebe</li>
			<li class="text-lg">Hermann Holstad Walaunet</li>
		</ul>

		<!-- V24 -->
		<ul class="list-none space-y-1 p-0 text-lg">
			<li class="text-lg">Jesper Kierulf Hammer</li>
		</ul>

		<!-- H24 -->
		<ul class="list-none space-y-1 p-0 text-lg">
			<li class="text-lg">Andreas Drevdal</li>
			<li class="text-lg">Birk Monsen</li>
		</ul>
	</div>
</Container>
