// apps/beta/src/routes/(app)/for-studenter/motereferater/+page.svelte
<script lang="ts">
	import { ArrowRight } from 'lucide-svelte';

	let { data } = $props();
</script>

<h1 class="mb-4 text-2xl font-medium">Møtereferater</h1>
<ul class="divide-y overflow-hidden rounded-xl border">
	{#each data.minutes as minute}
		<li>
			<a href="/for-studenter/motereferat/{minute._id}">
				<div
					class="hover:bg-muted group flex items-center justify-between px-5 py-5 transition-all hover:py-10"
				>
					<div class="flex w-full flex-col sm:flex-row sm:items-center sm:justify-between">
						<p class="text-xl">
							{#if minute.isAllMeeting}
								Generalforsamling
							{:else}
								Møte
							{/if}
						</p>

						<div class="flex items-center gap-2">
							<p>
								{new Date(minute.date).toLocaleDateString('nb-NO', {
									day: 'numeric',
									month: 'short',
									year: 'numeric',
									timeZone: 'Europe/Oslo'
								})}
							</p>
							<ArrowRight class="hidden h-8 w-8 rounded border p-2 sm:block" />
						</div>
					</div>

					<div class="block sm:hidden">
						<ArrowRight class="h-8 w-8 rounded border p-2" />
					</div>
				</div>
			</a>
		</li>
	{/each}
</ul>

// apps/web/src/app/(default)/for-studenter/motereferater/page.tsx
import { ArrowRight } from "lucide-react";
import Link from "next/link";

import { unoWithAdmin } from "@/api/server";
import { Container } from "@/components/container";
import { Heading } from "@/components/typography/heading";
import { Text } from "@/components/typography/text";
import { StaticPageSidebar } from "@/lib/static-page-sidebar";
import { shortDateNoTime } from "@/utils/date";

export default async function MinuteOverview() {
  const minutes = await unoWithAdmin.sanity.minutes.all().catch(() => []);

  return (
    <Container className="flex flex-row py-10">
      <StaticPageSidebar />

      <div className="flex-1">
        <Heading className="mb-4">Møtereferater</Heading>
        <ul className="divide-y overflow-hidden rounded-lg border">
          {minutes.map((minute) => (
            <li key={minute._id}>
              <Link href={"/for-studenter/motereferat/" + minute._id}>
                <div className="group hover:bg-muted flex items-center justify-between px-5 py-5 transition-all hover:py-10">
                  <div className="flex w-full flex-col sm:flex-row sm:items-center sm:justify-between">
                    <Text size="lg">{minute.isAllMeeting ? "Generalforsamling" : "Møte"}</Text>

                    <div className="flex items-center gap-2">
                      <p>{shortDateNoTime(minute.date)}</p>
                      <ArrowRight className="hidden h-8 w-8 rounded border p-2 sm:block" />
                    </div>
                  </div>

                  <div className="block sm:hidden">
                    <ArrowRight className="h-10 w-10 rounded border p-2" />
                  </div>
                </div>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </Container>
  );
}
