// apps/beta/src/lib/components/ui/form/checkbox.svelte
<script lang="ts">
	import { Checkbox, useId, type WithoutChildrenOrChild } from 'bits-ui';
	import { Check, Minus } from '@lucide/svelte';
	import { cn } from '$lib/cn';

	let {
		id: propId,
		class: className,
		name,
		checked = $bindable(false),
		ref = $bindable(null),
		...restProps
	}: WithoutChildrenOrChild<Checkbox.RootProps> = $props();
	const id = propId ?? name ?? useId();
</script>

<Checkbox.Root
	{id}
	class={cn(
		'flex size-4 items-center justify-center rounded-md border-2',
		'transition duration-200 ease-in-out',
		'focus:ring-primary focus:ring-2 focus:ring-offset-2 focus:outline-none',
		{
			'bg-primary text-primary-foreground border-transparent': checked
		},
		className
	)}
	bind:checked
	bind:ref
	{...restProps}
>
	{#snippet children({ checked, indeterminate })}
		{#if indeterminate}
			<Minus class="size-4 stroke-3" />
		{:else if checked}
			<Check class="size-4 stroke-3" />
		{/if}
	{/snippet}
</Checkbox.Root>

{#if name}
	<input type="hidden" {name} value={checked ? 'on' : 'off'} />
{/if}

// src/components/ui/checkbox.tsx
"use client";

import * as React from "react";
import * as CheckboxPrimitive from "@radix-ui/react-checkbox";
import { RxCheck as Check } from "react-icons/rx";

import { cn } from "@/utils/cn";

export const Checkbox = React.forwardRef<
  React.ElementRef<typeof CheckboxPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>
>(({ className, ...props }, ref) => (
  <CheckboxPrimitive.Root
    ref={ref}
    className={cn(
      "peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground",
      className,
    )}
    type="button"
    {...props}
  >
    <CheckboxPrimitive.Indicator className={cn("flex items-center justify-center text-current")}>
      <Check className="h-4 w-4" />
    </CheckboxPrimitive.Indicator>
  </CheckboxPrimitive.Root>
));
Checkbox.displayName = CheckboxPrimitive.Root.displayName;
